#+title: Crypt

* Password Manager
  - 1Password :: Private password managem.
  - [[https://www.passwordstore.org/][pass]] :: Password management should be simple and follow Unix
    philosophy. With pass, each password lives inside of a gpg encrypted file
    whose filename is the title of the website or resource that requires the
    password. These encrypted files may be organized into meaningful folder
    hierarchies, copied from computer to computer, and, in general, manipulated
    using standard command line file management utilities.
  - gopass ::
  - [[https://github.com/nuxsmin/sysPass][sysPass]] :: Gestor de Claves web basado en PHP para uso empresarial y personal.
  - more ::  see [[file:../network/service.org::#selfhost][selfhost]]

* PGP
Pretty Good Privacy is a nice way to crypt data.

** GnuPG
   A implement of pgp.
*** Auxiliary
    - gpg-tui :: It aims to ease the key management operations such as
      listing/exporting/signing by providing an interface along with the
      command-line fallback for more complex operations. It is not trying to be
      a full-fledged interface for all the features that gpg provides but it
      tries to bring a more interactive approach to key management.
*** Public Key Server
    :PROPERTIES:
    :ID:       053a7e7b-377d-4005-9dec-bb30acc27483
    :END:
    - [[http://keys.gnupg.net/][openpgp]] ::
    - [[http://pgp.mit.edu/][mit]] ::

** keybase
   Use PGP to send message, which like whatsapp but this won't manage you keys, so it is safter. A end-to-end encryption is the best way to exchange message.

   It also is a platform to show your public key. I love it!
