#+TITLE: Monitor
#+AUTHOR: Vonfry

See [[file:../development/deploy.org][development/deploy]] for complex tools.

* System
   - inxi :: system states, such as cpu, memory and etc
   - [[https://www.criu.org/Main_Page][CRIU]] :: Checkpoint/Restore In Userspace, or CRIU (pronounced kree-oo, IPA:
     /krɪʊ/, Russian: криу), is a Linux software. It can freeze a running
     container (or an individual application) and checkpoint its state to
     disk. The data saved can be used to restore the application and run it
     exactly as it was during the time of the freeze. Using this functionality,
     application or container live migration, snapshots, remote debugging, and
     many other things are now possible.
   - [[https://github.com/aristocratos/btop][btop]] ::  A monitor of resources
   - [[https://github.com/facebookincubator/below][below]] :: A time traveling resource monitor for modern Linux systems
   - bpftrace :: High-level tracing language for Linux eBPF
   - [[https://gitlab.com/mission-center-devs/mission-center][mission-center]] :: Monitor your CPU, Memory, Disk, Network and GPU usage
     with Mission Center
   - [[https://bjango.com/mac/istatmenus/][iStat Menus]] :: system status bar
* Monitor
   - netdata :: system resource monitor
   - [[https://oguzhaninan.github.io/Stacer-Web/][stacer]] :: Stacer is an open source system optimizer and application monitor
     that helps users to manage entire system with different aspects, its an all
     in one system utility.
   - [[https://github.com/prometheus/prometheus][prometheus]] :: Prometheus, a Cloud Native Computing Foundation project, is a
     systems and service monitoring system. It collects metrics from configured
     targets at given intervals, evaluates rule expressions, displays the
     results, and can trigger alerts if some condition is observed to be true.
   - [[https://osquery.io/][osquery]] :: Performant endpoint visibility
