stages:
  - build
  - deploy

default:
  image: ubuntu:devel
  cache:
    paths:
      - .build/
      - .cache/

build:
  before_script:
    - apt update
    - apt install -y emacs elpa-org elpa-org-roam
    - mkdir -p .build
    - mkdir -p .cache
    - mv .cache ~/.cache
  script:
    - emacs --batch -l .gitlab/build.el
  after_script:
    - mv ~/.cache .cache
  stage: build

pages:
  script:
    - mkdir public
    - cp -r .build/* public/
  stage: deploy
  only:
    - master
  artifacts:
    paths:
      - public
