stages:
  - build
  - deploy

default:
  image: ubuntu
  cache:
    paths:
      - .build/
      - .cache/

build:
  before_script:
    - apt update
    - apt install -y ca-cacert emacs graphviz sqlite3
    - mkdir -p .build
    - mv .cache ~/.cache
  script:
    - emacs readme.org --batch -l .gitlab/build.el
  after_script:
    - mv ~/.cache .cache
  stage: build

pages:
  script:
    - mkdir public
    - cp .build/roam.svg public/roam.svg
    - echo "<img src=roam.svg>" > public/index.html
  stage: deploy
  only:
    - master
  artifacts:
    paths:
      - public
