#+TITLE: Linux
#+AUTHOR: Vonfry


* Release
  - Gentoo :: A flexible, source-based Linux distribution that becomes just
    about any system you need—and much more. You can choose what you want to
    install with a package.
      - Anything(installation, development environment, overlay or others) about
        it can be fountd on its [[http://wiki.gentoo.org/][*wiki*]].
  - NixOS :: NixOS is a Linux distribution with a unique approach to package and
    configuration management. Built on top of the Nix package manager, it is
    completely declarative, makes upgrading systems reliable, and has many
    other advantages.
  - Kali :: Kali Linux Advanced Web Attacks and Exploitation
  - qubes os :: A reasonably secure operating system

  Both NixOS and Gentoo are my love. And the archlinux's wiki is the best wiki I
  think. Other distributions are used for special usage in virtual machine.

* Kernal patch
  - [[https://github.com/zen-kernel/zen-kernel][zen]] ::
  - other :: see gentoo hardened wiki

* Application
  Linux tools can be checked in shell and other topics as well.

** Remote(GUI)
   - freerdp :: rdp protocol remote connectiing util. This can connect to
     windows. On linux, you have to open a service first.
   - tigervnc :: vnc protocol to connect.
   - remmina :: Multiple protocol supporting client.
   - nomachine :: server and client, self protocol
   - rdesktop ::

** System
   - xidlehook :: a replacement for xautolock.
** Utils
   - qrencode :: qrcode encode
   - zbar :: qrcode decode
* Tutor
  - [[https://github.com/learnbyexample/Command-line-text-processing][CLI]] ::
  - [[https://linuxcommand.org][linuxcommand.org]] ::
* Philosophy
  - KISS Principle :: [[https://en.wikipedia.org/wiki/KISS_principle][keep it simple and silly]], [[https://web.archive.org/web/20210126090054/https://en.wikipedia.org/wiki/KISS_principle][archive]]
