#+title: Analyzer

* Web Log
  - goaccess :: A real-time web log analyzer and interactive viewer that runs in a terminal
  - rhit :: nginx log reader
  - more :: see [[file:service.org::#selfhost][selfhost]]

* Security
  - nmap :: port scan
  - nessus :: A remote security scanner
  - snort :: Snort is an intrusion prevention system, network monitor, and alert
    daemon.
  - ossec ::
  - mhn :: Modern Honey Network, MHN is a centralized server for management and
    data collection of honeypots. MHN allows you to deploy sensors quickly and
    to collect data immediately, viewable from a neat web interface. Honeypot
    deploy scripts include several common honeypot technologies, including
    Snort, Cowrie, Dionaea, and glastopf, among others.
  - [[https://github.com/FDio/vpp][vpp]] :: The VPP platform is an extensible framework that provides
    out-of-the-box production quality switch/router functionality. It is the
    open source version of Cisco's Vector Packet Processing (VPP) technology: a
    high performance, packet-processing stack that can run on commodity CPUs.

* Social
  - [[https://github.com/qeeqbox/social-analyzer][social analyzer]] :: OSINT
* Agent
  - [[https://github.com/huginn/huginn][huginn]] :: Create agents that monitor and act on your behalf. Your agents are standing by!
* Speed
  - speedtest-cli ::
  - iperf ::
